# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasons', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veg_name', models.CharField(max_length=50)),
                ('veg_type', models.CharField(max_length=50)),
                ('veg_image', models.CharField(max_length=25)),
                ('veg_desc', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Vegetable',
                'verbose_name_plural': 'Vegetables',
            },
        ),
        migrations.AddField(
            model_name='season',
            name='seasons_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FreshPoint.State'),
        ),
        migrations.AddField(
            model_name='season',
            name='seasons_veg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FreshPoint.Vegetable'),
        ),
    ]
