# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreshPoint', '0002_state_state_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state_full',
            field=models.CharField(max_length=15),
        ),
    ]
